// <auto-generated />
using System;
using EnqueueIt.MySql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnqueueIt.MySql.Migrations
{
    [DbContext(typeof(EnqueueItDbContext))]
    [Migration("20230413192955_CreateEnqueueItDatabase")]
    partial class CreateEnqueueItDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("EnqueueIt.Sql.BackgroundJobItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("JobError")
                        .HasColumnType("text")
                        .HasColumnName("job_error");

                    b.Property<string>("JobId")
                        .HasColumnType("char(36)")
                        .HasColumnName("job_id");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_activity");

                    b.Property<string>("Logs")
                        .HasColumnType("text")
                        .HasColumnName("logs");

                    b.Property<string>("ProcessedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("processed_by");

                    b.Property<string>("Server")
                        .HasColumnType("text")
                        .HasColumnName("server");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_background_jobs");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_background_jobs_job_id");

                    b.ToTable("background_jobs");
                });

            modelBuilder.Entity("EnqueueIt.Sql.JobItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<string>("AfterBackgroundJobIds")
                        .HasColumnType("text")
                        .HasColumnName("after_background_job_ids");

                    b.Property<string>("AppName")
                        .HasColumnType("text")
                        .HasColumnName("app_name");

                    b.Property<string>("Argument")
                        .HasColumnType("text")
                        .HasColumnName("argument");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_recurring");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Queue")
                        .HasColumnType("text")
                        .HasColumnName("queue");

                    b.Property<string>("Recurring")
                        .HasColumnType("text")
                        .HasColumnName("recurring");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_at");

                    b.Property<int>("Tries")
                        .HasColumnType("int")
                        .HasColumnName("tries");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.ToTable("jobs");
                });

            modelBuilder.Entity("EnqueueIt.Sql.BackgroundJobItem", b =>
                {
                    b.HasOne("EnqueueIt.Sql.JobItem", "Job")
                        .WithMany("BackgroundJobs")
                        .HasForeignKey("JobId")
                        .HasConstraintName("fk_background_jobs_jobs_job_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("EnqueueIt.Sql.JobItem", b =>
                {
                    b.Navigation("BackgroundJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
